import Head from 'next/head'
import { Inter } from 'next/font/google'


import Row from '@/components/row/Row'
import { getUpcoming, getTopRated } from '@/lib/data'
import { useEffect, useState } from 'react'

const inter = Inter({ subsets: ['latin'] })


export default function Home() {

  const [upcoming, setUpcoming] = useState();
  const [toprated, setToprated] = useState();

  useEffect(() => {
    getUpcoming().then(data => setUpcoming(data?.results));
    getTopRated().then(data => setToprated(data?.results));
  }, [])

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="">
        <Row title='Upcomming' data={upcoming} />
        <Row title='Top Rated' data={toprated} />
      </main>
    </>
  )
}
